language: cpp

compiler:
  - gcc
  - clang
  
env:
  - QT_VER=4
  - QT_VER=5

matrix:
  allow_failures:
    - env: QT_VER=5
      compiler: clang

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - if [ "$QT_VER" == "5" ]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa; fi
  - sudo apt-get update -qq

install:
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/clang++-3.4 90; fi
  - if [ "$QT_VER" == "5" ]; then sudo apt-get install qt5-qmake qt5-default; fi

script:
  - qmake -v
  - cd src
  - qmake tyrex.pro
  - make
